### PR TITLE
55 content retrieval bug in the form

### PR DESCRIPTION
**Pull request by gaeVG**
I think that since the last updates, the category retrieval was no longer working properly; the problem has been solved by filtering on the available contexts and the respective item IDs

### CODE REVIEW

**Comment by gaeVG** [comment]
I just found a bug with the references to be modified but I can't decide: I think we should retrieve the content of the references we get from the dashboard, but we could as well retrieve the bare minimum to display only the information to be displayed (title, contributor, modification date, etc.) and request the API to process the reference in the form component.

@Lauraillouz, if you have an opinion on this.

**Comment by Lauraillouz** [comment]
You explained to me the two options, but not the problem :) Can you give me details about it with a screenshot so I can understand the extend of it?

**Comment by gaeVG** [comment]
> You explained to me the two options, but not the problem :) Can you give me details about it with a screenshot so I can understand the extend of it?

The content of the form, either for creating or modifying a reference, was no longer automatically filled in, which can be problematic for modifying an existing reference when the content does not appear

**Comment by Lauraillouz** [comment]
So I think we need to get the reference's information only when we click on it and not beforehand. Otherwise it makes the loading of the list of references carry more data than needed.

**Pull request merged**
